from architecture.configs.encoderConfig import EncoderConfig
from architecture.configs.decoderConfig import DecoderConfig
from architecture.configs.lstmConfig import LSTMConfig
from architecture.configs.modelConfig import ModelConfig